// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    return $2w.controller('quickdemo', function(scope) {
      return scope.dollar = function() {
        return scope.name * 1.0661;
      };
    });
  });

}).call(this);
